name: Pack and Publish OCI Image to Docker Registry

on:
  push:
    branches:
      - main
      - master
      - rudransh404
  workflow_dispatch:
    inputs:
      workflow_choice:
        description: "Choose Release Channel"
        required: true
        default: "edge"
        type: choice
        options:
          - edge
          - stable
          - both
  workflow_run:
    workflows: ["Push new tag update to stable branch"]
    types:
      - completed

jobs:
  build-rock:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pack with Rockcraft
        uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - name: Upload Rock Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cups-rock
          path: ${{ steps.rockcraft.outputs.rock }}

  publish-rock:
    needs: build-rock
    if: github.ref_name == 'main' || github.ref_name == 'master' || github.ref_name == 'rudransh404'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Rock Artifact
        uses: actions/download-artifact@v4
        with:
          name: cups-rock

      - name: Install Dependencies
        run: |
          sudo snap install rockcraft --classic
          sudo snap install docker
          sudo snap install yq

      - name: Ensure Docker Daemon is Running
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo systemctl is-active --quiet docker || sudo systemctl start docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: rudransh404
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image (Edge & Latest Channel)
        if: github.event.inputs.workflow_choice == 'edge' || github.event.inputs.workflow_choice == 'both' || github.event_name == 'push' || github.event_name == 'workflow_run'
        run: |
          IMAGE="$(yq '.name' rockcraft.yaml)"
          VERSION="$(yq '.version' rockcraft.yaml)"
          ROCK="$(ls *.rock | tail -n 1)"
          sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${ROCK}" docker-daemon:"rudransh404/${IMAGE}:${VERSION}-edge"
          docker push rudransh404/${IMAGE}:${VERSION}-edge
          docker tag rudransh404/${IMAGE}:${VERSION}-edge rudransh404/${IMAGE}:latest
          docker push rudransh404/${IMAGE}:latest

      - name: Build and Push Docker Image (Stable Channel)
        if: github.event.inputs.workflow_choice == 'stable' || github.event.inputs.workflow_choice == 'both'
        run: |
            IMAGE="$(yq '.name' rockcraft.yaml)"
            VERSION="$(yq '.version' rockcraft.yaml)"
            ROCK="$(ls *.rock | tail -n 1)"
            sudo rockcraft.skopeo --insecure-policy copy oci-archive:"${ROCK}" docker-daemon:"rudransh404/${IMAGE}:${VERSION}-stable"
            # Push to Docker Hub
            docker push rudransh404/${IMAGE}:${VERSION}-stable
